### ISSUE TITLE
Colorscheme name issue

### ISSUE THREAD

**Issue by kgmyatthu** [Abstract-IDE/Abstract-cs#4]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24825299/196049161-7afab81f-a9e5-4861-a3fc-f130a437f7e9.png">

**Comment by shaeinst** [comment]
sorry this repository was renamed and i forgot to update the README. it's updated now.
it should be `vim.cmd[[colorscheme abscs]]`

**Comment by kgmyatthu** [comment]
Awesome theme, thanks.
