### ISSUE TITLE
Better Telescope support?

### ISSUE THREAD

**Issue by tmpm697** [Abstract-IDE/Abstract-cs#5]
I like this colorscheme but would be nice if can add more support for `Telescope` like: [this](https://www.reddit.com/r/neovim/comments/se377t/telescopenvim_looks_neat/) and [this](https://www.reddit.com/r/neovim/comments/xcsatv/how_can_i_configure_telescope_to_look_like_this/)

**Comment by shaeinst** [comment]
i am following the design pattern of this color scheme.  I use telescope very frequently and so it should be very clear when i open it.Would you please point out what exactly changes I should make?

**Comment by tmpm697** [comment]
the border and background color. the search box also different from other.

this colorscheme currently use same bg for both buffer and telescope, use a line border to distinguish instead of different background colors.

**Comment by shaeinst** [comment]
border is little dark than other and can be little light but background is same for all
> the border and background color. the search box also different from other.

are you sure because background of current line row, status line and buffer line are same. and border color for telescope can be little more strong though.
>this colorscheme currently use same bg for both buffer and telescope

**Comment by tmpm697** [comment]
yeah background should be stronger to distinguish with background of buffer and others. Idk but the two links I mentioned should clear it.

**Comment by shaeinst** [comment]
https://github.com/Abstract-IDE/Abstract-cs/commit/8139d6f2cf1ff96108be70d1f43e22225c037390

**Comment by tmpm697** [comment]
"#3f3f3f" is ok :)
