### ISSUE TITLE
Wrong output of command :colorscheme

### ISSUE THREAD

**Issue by palandovalex** [Abstract-IDE/Abstract-cs#6]
I installed plugin your plugin I try add to config:
lvim.colorscheme = "abscs"
When i open lvim to edit file, theme is active. but when i try to check current theme with :colo command - it prints "default".

LunarVim version
https://github.com/LunarVim/LunarVim/commit/a7e7f28639a70ac56d77867c283c3666cae8ab4d

Package: neovim
Version: 0.9.0~ubuntu1+git202302261603-ed58580df-333b5866f-0853f7595~ubuntu22.04.1

Operating system/version
ubuntu22.04.1

**Comment by tan-wei** [comment]
Seems #10 is duplicated. Yes, I think it is a bug.

**Comment by shaeinst** [comment]
i forked `Abstract-cs` years ago and never focused on the logic flow this plugin. 
i have [fixed](https://github.com/Abstract-IDE/Abstract-cs/commit/07475aa22943dc25080239c8cab613ab0a2945df) it, so it should be working now.

**Comment by tan-wei** [comment]
OK, I'll try it now.

**Comment by tan-wei** [comment]
Fixed I can confirm. Should be closed.
