### ISSUE TITLE
Is this how it should be?

### ISSUE THREAD

**Issue by WinstonMDP** [Abstract-IDE/Abstract-cs#7]
![screen-1679489291](https://user-images.githubusercontent.com/61916541/226909867-77bd546f-f7d8-4a37-955a-edc9a0c120b6.png)

**Comment by shaeinst** [comment]
yep. install treesitter parser for rust for better syntax highlighting.

please note that  status bar, line number, line column etc should have to be configured independently from theme itself. you're not seeing these because you haven't configure it yet.

**Comment by WinstonMDP** [comment]
I just asked to see if treesitter works for me. Can you please see what I did wrong in my config in dotfiles repository? I've been trying to figure out what's wrong, but I haven't been able to yet

**Comment by shaeinst** [comment]
ok let me see it but please leave links to your dot files here.

**Comment by WinstonMDP** [comment]
https://github.com/WinstonMDP/dotfiles

**Comment by shaeinst** [comment]
i think treesitter is working (in screenshot you provided). why do you think it's not working??
you can test it by removing `rust` from ensure_installed and manually installing and uninstalling rust parser
`: TSInstall rust`
```lua
require('nvim-treesitter.configs').setup {
    ensure_installed = { "rust", "toml", "latex", "bibtex", "lua", "markdown", "dockerfile", "vim" },
    auto_install = true,
    highlight = { enable = true }
}
```

**Comment by WinstonMDP** [comment]
I wasn't sure. But when you said "install treesitter parser", I was confirmed in the thought

**Comment by shaeinst** [comment]
so are we good now? can we close this issue?

**Comment by WinstonMDP** [comment]
Yes. Thanks a lot)
